version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reseau

  script:
    image: php:8.3.7-fpm
    container_name: script
    volumes:
      - ./app:/app
    networks:
      - reseau
    command: bash -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && php-fpm"

  http:
    image: nginx:1.25
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - reseau

volumes:
  db_data:

networks:
  reseau:
